INSERT INTO USER VALUES ('blancadepedr','Blanca','{noop}password','blancadepedr@gmail.com',20);
INSERT INTO SONG VALUES('ID','NAME','ARTIST','ALBUM',1);
INSERT INTO ALBUM VALUES('ID','NAME','ARTIST','DATE','IMAGE',10);
INSERT INTO ARTIST VALUES('ID','NAME','IMAGE','GENRES',100); 
INSERT INTO EPISODE VALUES('ID','NAME','P','D','I',89);