DROP TABLE IF EXISTS USER;

CREATE TABLE "USER"(
    "USER_ID" VARCHAR(45) NOT NULL,
    "USER_NAME" VARCHAR(45) NOT NULL,
    "USER_PASSWORD" VARCHAR(45) NOT NULL,
    "USER_EMAIL" VARCHAR(45) NOT NULL,
    "USER_AGE" NUMERIC NOT NULL
);
